services:
  line-pregnant:
    build: .
    ports:
      - "3012:3001"
    environment:
      - TZ=Asia/Bangkok
      - DATABASE_URL=postgresql://play2:123456@localhost:5444/linedb?schema=public
    networks:
      - dev_network


networks:
  dev_network:
    external: true